export default [
  {
    bg: "#5D1D88",
    color: "#FFB700",
    category: "Electronics",
    subCategories: [
      "Camera & Photo",
      "Car & Vehicle Electronics",
      "Cell Phones & Accessories",
      "Computer & Accessories",
    ],
  },
  {
    bg: "#F04DA1",
    color: "#005EAB",
    category: "Computers",
    subCategories: [
      "Computer Accessories & Peripherals",
      "Computer Components",
      "Computers & Tablets",
      "Data Storages",
      "External Components",
      "Monitors",
      "Laptop Accessories",
      "Networking products",
      "Operating Systems",
    ],
  },
  {
    bg: "#FCB61A",
    color: "#0171CE",
    category: "Automotive",
    subCategories: [
      "Car Care",
      "Car Electronics & Accessories",
      "Exterior Accessories",
      "Oils & Fluids",
    ],
  },
  {
    bg: "#87575C",
    color: "#D1DFBB",
    category: "Arts & Crafts",
    subCategories: [
      "Painting, Drawing & Art Supplies",
      "Beading & Jewelry Making",
      "Crafting",
      "Fabric",
      "Fabric Decorating",
      "Knitting & Crochet",
      "NeedleWork",
      "Sewing",
      "Party Decoration & Supplies",
      "Gift Wrapping Supplies",
    ],
  },
  {
    bg: "#0A3D33",
    color: "#F4F3F0",
    category: "Toys & Games",
    subCategories: [
      "Action Figures & Statues",
      "Arts & Crafts",
      "Games",
      "Grown-Up Toys",
      "Hobbies",
      "Puzzles",
      "Video Games",
    ],
  },
];
